[book]
authors = ["Kevin Sullivan"]
language = "en"
multilingual = false
src = "src"
title = "Discrete Mathematics and Theory in Lean 4"

[tags]
"1.0.0" = { "releaseNotes" = "Empty Book", "releaseDate" = "Foo" }
"1.1.0" = { releaseNotes = "Chapters on Propositional Logic and Model Theory", release_date = "2025-01-15" }
"1.1.1" = { releaseNotes = "Fixes import paths in hw3", release_date = "2025-01-23" }

[build]
build-dir = "book"

[output.html]
additional-js = [
    "assets/lean.min.js",
    "assets/mermaid.min.js",
    "assets/mermaid-init.js",
]

# additional-css = ["assets/mermaid.css"]

mathjax-support = true
git-repository-url = "https://github.com/kevinsullivan/dmtl4"

[output.html.playground.boring-prefixes]
lean = "# "

[preprocessor.toc]
command = "mdbook-toc"
depth = 2

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]
